version: 2

project_name: cli_chat_app

builds:
  - id: linux_build
    main: ./cmd/client/main.go
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1

  - id: windows_build
    main: ./cmd/client/main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc

release:
  github:
    owner: Johnkhk
    name: cli_chat_app

changelog:
  sort: asc
