version: 2  # Specify the configuration version

project_name: cli_chat_app

builds:
  - id: cli_chat_app_build
    main: ./cmd/client/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude windows/arm64 due to complexity
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1
      - |
        CC={{- if and (eq .Os "linux") (eq .Arch "arm64") -}}
          aarch64-linux-gnu-gcc
        {{- else if and (eq .Os "windows") (eq .Arch "amd64") -}}
          {{- if eq .Env.RUNNER_OS "Linux" -}}
            x86_64-w64-mingw32-gcc
          {{- else -}}
            gcc
          {{- end -}}
        {{- else if eq .Os "darwin" -}}
          clang
        {{- else -}}
          gcc
        {{- end -}}

archives:
  - id: cli_chat_app_archive
    builds:
      - cli_chat_app_build
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: Johnkhk
    name: cli_chat_app

changelog:
  sort: asc
