version: 2

project_name: cli_chat_app

builds:
  - id: darwin_build
    main: ./cmd/client/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1

release:
  github:
    owner: Johnkhk
    name: cli_chat_app

changelog:
  sort: asc 