version: 2  # Specify the configuration version

project_name: cli_chat_app

builds:
  - id: cli_chat_app_build  # Assign an ID to the build
    main: ./cmd/client/main.go  # Path to your main Go file
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1  # Enable CGO

archives:
  - id: cli_chat_app_archive  # Assign an ID to the archive
    builds:
      - cli_chat_app_build  # Reference the build ID
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    # No need to exclude dist/** since it's not being included

release:
  github:
    owner: Johnkhk
    name: cli_chat_app

changelog:
  sort: asc
