version: 2

project_name: cli_chat_app

builds:
  - id: darwin_build
    main: ./cmd/client/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1

  - id: linux_windows_build
    main: ./cmd/client/main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - "-X 'main.defaultServerAddress={{.Env.SERVER_ADDRESS}}'"
    env:
      - CGO_ENABLED=1
      - |
        CC={{- if eq .Os "windows" -}}
          x86_64-w64-mingw32-gcc
        {{- else -}}
          gcc
        {{- end -}}

archives:
  - id: linux_windows_archive
    builds:
      - linux_windows_build
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  - id: darwin_archive
    builds:
      - darwin_build
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: Johnkhk
    name: cli_chat_app

changelog:
  sort: asc
