version: '3.8'

services:
  server:
    image: "johnkhh/cli-chat-app-server:latest"
    pull_policy: always

    ports:
      - "50051:50051"
    environment:
      - ENV_PATH=.env
      - PORT=${PORT}
      - CLI_CHAT_APP_JWT_SECRET_KEY=${CLI_CHAT_APP_JWT_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    networks:
      - chat-network

  db:
    image: mysql:8.0
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 50051
      MYSQL_DATABASE: cli_chat_app
      MYSQL_USER: cli_chat_dev
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-data: