name: Client Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Grant write permissions to contents

jobs:
  release:
    name: Release binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Update to your Go version

      - name: Install Cross-Compilers (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64

      - name: Set SERVER_ADDRESS with Port
        run: echo "SERVER_ADDRESS=${{ secrets.EC2_HOST }}:50051" >> $GITHUB_ENV

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true

      - name: Check GoReleaser Version
        run: goreleaser --version

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_ADDRESS: ${{ env.SERVER_ADDRESS }}
        run: goreleaser release --clean --rm-dist
