name: Client Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Grant write permissions to contents

jobs:
  release:
    name: Release binaries
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Cross-Compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true

      - name: Set SERVER_ADDRESS with Port
        run: echo "SERVER_ADDRESS=${{ secrets.EC2_HOST }}:50051" >> $GITHUB_ENV

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_ADDRESS: ${{ env.SERVER_ADDRESS }}
          CC: aarch64-linux-gnu-gcc  # Set the cross-compiler for arm64
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean

