name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod env  # Specify the environment (in github settings)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cli-chat-app-server:latest